language: minimal
if: head_branch = v1beta_oci_spec_update OR branch = v1beta_oci_spec

services:
  - docker

env:
  global:
    - DOCKER_HUB_AGENT_TAG="enterpriseconnect/agent:v1beta"
    - DOCKER_HUB_PLUGIN_TAG="enterpriseconnect/plugins:v1beta"
    - DOCKER_HUB_BUILD_TAG="enterpriseconnect/build:v1beta"
    - GITHUB_AGENT_TAG="docker.pkg.github.com/ec-release/oci/agent:v1beta"
    - GITHUB_PLUGIN_TAG="docker.pkg.github.com/ec-release/oci/plugins:v1beta"
    - GITHUB_BUILD_TAG="docker.pkg.github.com/ec-release/oci/build:v1beta"
    - GITHUB_REGISTRY="https://docker.pkg.github.com"
    - GITHUB_USR="ayasuda-ge"
    
before_install:

script:
   - cd ./spec/agent && docker build -t $DOCKER_HUB_AGENT_TAG --build-arg EC_REV_V1BETA=${EC_REV_V1BETA} . && cd -
   - cd ./spec/plugin && docker build -t $DOCKER_HUB_PLUGIN_TAG --build-arg EC_REV_V1BETA=${EC_REV_V1BETA} . && cd -
   - cd ./spec/build && docker build -t $DOCKER_HUB_BUILD_TAG --build-arg EC_REV_V1BETA=${EC_REV_V1BETA} . && cd -
   
deploy:
  - provider: script
    skip_cleanup: true
    script: >-
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin &&
      docker push $DOCKER_HUB_AGENT_TAG && 
      docker push $DOCKER_HUB_PLUGIN_TAG &&
      docker push $DOCKER_HUB_BUILD_TAG &&
      docker tag $DOCKER_HUB_AGENT_TAG $GITHUB_AGENT_TAG &&
      docker tag $DOCKER_HUB_PLUGIN_TAG $GITHUB_PLUGIN_TAG &&
      docker tag $DOCKER_HUB_BUILD_TAG $GITHUB_BUILD_TAG &&
      echo $GITHUB_DOCKER_TKN_V1BETA | docker login $GITHUB_REGISTRY -u $GITHUB_USR --password-stdin &&
      docker push $GITHUB_AGENT_TAG &&
      docker push $GITHUB_PLUGIN_TAG &&
      docker push $GITHUB_BUILD_TAG
    on:
      branch: v1beta_oci_spec

after_deploy: >-
  docker run -it $DOCKER_HUB_AGENT_TAG -ver && docker rmi $DOCKER_HUB_AGENT_TAG -f && 
  docker run -it $DOCKER_HUB_PLUGIN_TAG -inf && docker rmi $DOCKER_HUB_PLUGIN_TAG -f &&
  docker rmi $DOCKER_HUB_BUILD_TAG -f && docker run -it $DOCKER_HUB_BUILD_TAG go version
notifications:  
  email:  
    recipients:  
    - ec-research@ge.com
    #- enterprise-connect@ge.com
    on_success: always  
    on_failure: always
